name: "Run cargo-msrv"
on:
  workflow_dispatch:
  push:
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    branches: ["**", "!v2"]

jobs:
  cargo-msrv:
    permissions:
      contents: write
      pull-requests: write
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@f1b8454b2bc79552b18b430b9018bd88fbb6190b # main
