name: "Run cargo-msrv"
on:
  workflow_dispatch:
  push:
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    branches: ["**", "!v2"]

jobs:
  cargo-msrv:
    permissions:
      contents: write
      pull-requests: write
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@bead95cfe6bf9f5920d5e7b0056f49870d9e3cc4 # main
